parameters:
    Ibram_report.reportService.class: Ibram\Core\ReportBundle\Service\ReportService

services:
    Ibram_report.reportService:
        class: %Ibram_report.reportService.class%
        arguments: ["@doctrine.orm.entity_manager"]
