parameters:
#    san_sis_core_report.example.class: SanSIS\Core\ReportBundle\Example

services:
#    san_sis_core_report.example:
#        class: %san_sis_core_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
