parameters:
    SanSIS_report.reportService.class: SanSIS\Core\ReportBundle\Service\ReportService

services:
    SanSIS_report.reportService:
        class: %SanSIS_report.reportService.class%
        arguments: ["@doctrine.orm.entity_manager"]
